(cl:in-package robot_base_controller-msg)
(cl:export '(FRONT_RIGHT_ENCODER_DATA-VAL
          FRONT_RIGHT_ENCODER_DATA
          FRONT_LEFT_ENCODER_DATA-VAL
          FRONT_LEFT_ENCODER_DATA
          REAR_RIGHT_ENCODER_DATA-VAL
          REAR_RIGHT_ENCODER_DATA
          REAR_LEFT_ENCODER_DATA-VAL
          REAR_LEFT_ENCODER_DATA
))