// Generated by gencpp from file robot_base_controller/encoder_data.msg
// DO NOT EDIT!


#ifndef ROBOT_BASE_CONTROLLER_MESSAGE_ENCODER_DATA_H
#define ROBOT_BASE_CONTROLLER_MESSAGE_ENCODER_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_base_controller
{
template <class ContainerAllocator>
struct encoder_data_
{
  typedef encoder_data_<ContainerAllocator> Type;

  encoder_data_()
    : front_right_encoder_data(0.0)
    , front_left_encoder_data(0.0)
    , rear_right_encoder_data(0.0)
    , rear_left_encoder_data(0.0)  {
    }
  encoder_data_(const ContainerAllocator& _alloc)
    : front_right_encoder_data(0.0)
    , front_left_encoder_data(0.0)
    , rear_right_encoder_data(0.0)
    , rear_left_encoder_data(0.0)  {
  (void)_alloc;
    }



   typedef float _front_right_encoder_data_type;
  _front_right_encoder_data_type front_right_encoder_data;

   typedef float _front_left_encoder_data_type;
  _front_left_encoder_data_type front_left_encoder_data;

   typedef float _rear_right_encoder_data_type;
  _rear_right_encoder_data_type rear_right_encoder_data;

   typedef float _rear_left_encoder_data_type;
  _rear_left_encoder_data_type rear_left_encoder_data;





  typedef boost::shared_ptr< ::robot_base_controller::encoder_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_base_controller::encoder_data_<ContainerAllocator> const> ConstPtr;

}; // struct encoder_data_

typedef ::robot_base_controller::encoder_data_<std::allocator<void> > encoder_data;

typedef boost::shared_ptr< ::robot_base_controller::encoder_data > encoder_dataPtr;
typedef boost::shared_ptr< ::robot_base_controller::encoder_data const> encoder_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_base_controller::encoder_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_base_controller::encoder_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_base_controller::encoder_data_<ContainerAllocator1> & lhs, const ::robot_base_controller::encoder_data_<ContainerAllocator2> & rhs)
{
  return lhs.front_right_encoder_data == rhs.front_right_encoder_data &&
    lhs.front_left_encoder_data == rhs.front_left_encoder_data &&
    lhs.rear_right_encoder_data == rhs.rear_right_encoder_data &&
    lhs.rear_left_encoder_data == rhs.rear_left_encoder_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_base_controller::encoder_data_<ContainerAllocator1> & lhs, const ::robot_base_controller::encoder_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_base_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_base_controller::encoder_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_base_controller::encoder_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_base_controller::encoder_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_base_controller::encoder_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_base_controller::encoder_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_base_controller::encoder_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_base_controller::encoder_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8bd3a66bc403e0d2c70d6f2f2b5db75";
  }

  static const char* value(const ::robot_base_controller::encoder_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8bd3a66bc403e0dULL;
  static const uint64_t static_value2 = 0x2c70d6f2f2b5db75ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_base_controller::encoder_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_base_controller/encoder_data";
  }

  static const char* value(const ::robot_base_controller::encoder_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_base_controller::encoder_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# encoder_data.msg\n"
"float32 front_right_encoder_data\n"
"float32 front_left_encoder_data\n"
"float32 rear_right_encoder_data\n"
"float32 rear_left_encoder_data\n"
;
  }

  static const char* value(const ::robot_base_controller::encoder_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_base_controller::encoder_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.front_right_encoder_data);
      stream.next(m.front_left_encoder_data);
      stream.next(m.rear_right_encoder_data);
      stream.next(m.rear_left_encoder_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct encoder_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_base_controller::encoder_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_base_controller::encoder_data_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "front_right_encoder_data: ";
    Printer<float>::stream(s, indent + "  ", v.front_right_encoder_data);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "front_left_encoder_data: ";
    Printer<float>::stream(s, indent + "  ", v.front_left_encoder_data);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rear_right_encoder_data: ";
    Printer<float>::stream(s, indent + "  ", v.rear_right_encoder_data);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rear_left_encoder_data: ";
    Printer<float>::stream(s, indent + "  ", v.rear_left_encoder_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_BASE_CONTROLLER_MESSAGE_ENCODER_DATA_H
