// Generated by gencpp from file robot_base_controller/velocity_data.msg
// DO NOT EDIT!


#ifndef ROBOT_BASE_CONTROLLER_MESSAGE_VELOCITY_DATA_H
#define ROBOT_BASE_CONTROLLER_MESSAGE_VELOCITY_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_base_controller
{
template <class ContainerAllocator>
struct velocity_data_
{
  typedef velocity_data_<ContainerAllocator> Type;

  velocity_data_()
    : front_left_wheel(0.0)
    , front_right_wheel(0.0)
    , rear_left_wheel(0.0)
    , rear_right_wheel(0.0)  {
    }
  velocity_data_(const ContainerAllocator& _alloc)
    : front_left_wheel(0.0)
    , front_right_wheel(0.0)
    , rear_left_wheel(0.0)
    , rear_right_wheel(0.0)  {
  (void)_alloc;
    }



   typedef double _front_left_wheel_type;
  _front_left_wheel_type front_left_wheel;

   typedef double _front_right_wheel_type;
  _front_right_wheel_type front_right_wheel;

   typedef double _rear_left_wheel_type;
  _rear_left_wheel_type rear_left_wheel;

   typedef double _rear_right_wheel_type;
  _rear_right_wheel_type rear_right_wheel;





  typedef boost::shared_ptr< ::robot_base_controller::velocity_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_base_controller::velocity_data_<ContainerAllocator> const> ConstPtr;

}; // struct velocity_data_

typedef ::robot_base_controller::velocity_data_<std::allocator<void> > velocity_data;

typedef boost::shared_ptr< ::robot_base_controller::velocity_data > velocity_dataPtr;
typedef boost::shared_ptr< ::robot_base_controller::velocity_data const> velocity_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_base_controller::velocity_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_base_controller::velocity_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_base_controller::velocity_data_<ContainerAllocator1> & lhs, const ::robot_base_controller::velocity_data_<ContainerAllocator2> & rhs)
{
  return lhs.front_left_wheel == rhs.front_left_wheel &&
    lhs.front_right_wheel == rhs.front_right_wheel &&
    lhs.rear_left_wheel == rhs.rear_left_wheel &&
    lhs.rear_right_wheel == rhs.rear_right_wheel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_base_controller::velocity_data_<ContainerAllocator1> & lhs, const ::robot_base_controller::velocity_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_base_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_base_controller::velocity_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_base_controller::velocity_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_base_controller::velocity_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_base_controller::velocity_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_base_controller::velocity_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_base_controller::velocity_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_base_controller::velocity_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6398bc5e122606acb80413c64aee32c3";
  }

  static const char* value(const ::robot_base_controller::velocity_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6398bc5e122606acULL;
  static const uint64_t static_value2 = 0xb80413c64aee32c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_base_controller::velocity_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_base_controller/velocity_data";
  }

  static const char* value(const ::robot_base_controller::velocity_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_base_controller::velocity_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# velocity_data.msg\n"
"float64 front_left_wheel\n"
"float64 front_right_wheel\n"
"float64 rear_left_wheel\n"
"float64 rear_right_wheel\n"
;
  }

  static const char* value(const ::robot_base_controller::velocity_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_base_controller::velocity_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.front_left_wheel);
      stream.next(m.front_right_wheel);
      stream.next(m.rear_left_wheel);
      stream.next(m.rear_right_wheel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct velocity_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_base_controller::velocity_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_base_controller::velocity_data_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "front_left_wheel: ";
    Printer<double>::stream(s, indent + "  ", v.front_left_wheel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "front_right_wheel: ";
    Printer<double>::stream(s, indent + "  ", v.front_right_wheel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rear_left_wheel: ";
    Printer<double>::stream(s, indent + "  ", v.rear_left_wheel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rear_right_wheel: ";
    Printer<double>::stream(s, indent + "  ", v.rear_right_wheel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_BASE_CONTROLLER_MESSAGE_VELOCITY_DATA_H
