// Generated by gencpp from file robot_scheduler/Object.msg
// DO NOT EDIT!


#ifndef ROBOT_SCHEDULER_MESSAGE_OBJECT_H
#define ROBOT_SCHEDULER_MESSAGE_OBJECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace robot_scheduler
{
template <class ContainerAllocator>
struct Object_
{
  typedef Object_<ContainerAllocator> Type;

  Object_()
    : object(0)
    , target(0)
    , decoy(false)
    , pose()  {
    }
  Object_(const ContainerAllocator& _alloc)
    : object(0)
    , target(0)
    , decoy(false)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef uint16_t _object_type;
  _object_type object;

   typedef uint16_t _target_type;
  _target_type target;

   typedef uint8_t _decoy_type;
  _decoy_type decoy;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::robot_scheduler::Object_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_scheduler::Object_<ContainerAllocator> const> ConstPtr;

}; // struct Object_

typedef ::robot_scheduler::Object_<std::allocator<void> > Object;

typedef boost::shared_ptr< ::robot_scheduler::Object > ObjectPtr;
typedef boost::shared_ptr< ::robot_scheduler::Object const> ObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_scheduler::Object_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_scheduler::Object_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_scheduler::Object_<ContainerAllocator1> & lhs, const ::robot_scheduler::Object_<ContainerAllocator2> & rhs)
{
  return lhs.object == rhs.object &&
    lhs.target == rhs.target &&
    lhs.decoy == rhs.decoy &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_scheduler::Object_<ContainerAllocator1> & lhs, const ::robot_scheduler::Object_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_scheduler

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_scheduler::Object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_scheduler::Object_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_scheduler::Object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_scheduler::Object_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_scheduler::Object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_scheduler::Object_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_scheduler::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18be81d5b846c94202e651e2dbb94986";
  }

  static const char* value(const ::robot_scheduler::Object_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18be81d5b846c942ULL;
  static const uint64_t static_value2 = 0x02e651e2dbb94986ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_scheduler::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_scheduler/Object";
  }

  static const char* value(const ::robot_scheduler::Object_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_scheduler::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 object\n"
"uint16 target\n"
"bool decoy\n"
"geometry_msgs/PoseStamped pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::robot_scheduler::Object_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_scheduler::Object_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object);
      stream.next(m.target);
      stream.next(m.decoy);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Object_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_scheduler::Object_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_scheduler::Object_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "object: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.object);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.target);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "decoy: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.decoy);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SCHEDULER_MESSAGE_OBJECT_H
