// Generated by gencpp from file robot_scheduler/SchedulerCommand.msg
// DO NOT EDIT!


#ifndef ROBOT_SCHEDULER_MESSAGE_SCHEDULERCOMMAND_H
#define ROBOT_SCHEDULER_MESSAGE_SCHEDULERCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace robot_scheduler
{
template <class ContainerAllocator>
struct SchedulerCommand_
{
  typedef SchedulerCommand_<ContainerAllocator> Type;

  SchedulerCommand_()
    : header()
    , uid(0)
    , target()
    , payload()
    , need_ack(false)  {
    }
  SchedulerCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , uid(0)
    , target(_alloc)
    , payload(_alloc)
    , need_ack(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint64_t _uid_type;
  _uid_type uid;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _target_type;
  _target_type target;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _payload_type;
  _payload_type payload;

   typedef uint8_t _need_ack_type;
  _need_ack_type need_ack;





  typedef boost::shared_ptr< ::robot_scheduler::SchedulerCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_scheduler::SchedulerCommand_<ContainerAllocator> const> ConstPtr;

}; // struct SchedulerCommand_

typedef ::robot_scheduler::SchedulerCommand_<std::allocator<void> > SchedulerCommand;

typedef boost::shared_ptr< ::robot_scheduler::SchedulerCommand > SchedulerCommandPtr;
typedef boost::shared_ptr< ::robot_scheduler::SchedulerCommand const> SchedulerCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_scheduler::SchedulerCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_scheduler::SchedulerCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_scheduler::SchedulerCommand_<ContainerAllocator1> & lhs, const ::robot_scheduler::SchedulerCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.uid == rhs.uid &&
    lhs.target == rhs.target &&
    lhs.payload == rhs.payload &&
    lhs.need_ack == rhs.need_ack;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_scheduler::SchedulerCommand_<ContainerAllocator1> & lhs, const ::robot_scheduler::SchedulerCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_scheduler

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_scheduler::SchedulerCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_scheduler::SchedulerCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_scheduler::SchedulerCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_scheduler::SchedulerCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_scheduler::SchedulerCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_scheduler::SchedulerCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_scheduler::SchedulerCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c8e7e95e708dac0be8b710a396741c1";
  }

  static const char* value(const ::robot_scheduler::SchedulerCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c8e7e95e708dac0ULL;
  static const uint64_t static_value2 = 0xbe8b710a396741c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_scheduler::SchedulerCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_scheduler/SchedulerCommand";
  }

  static const char* value(const ::robot_scheduler::SchedulerCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_scheduler::SchedulerCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint64 uid\n"
"string target\n"
"string payload\n"
"bool need_ack\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::robot_scheduler::SchedulerCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_scheduler::SchedulerCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.uid);
      stream.next(m.target);
      stream.next(m.payload);
      stream.next(m.need_ack);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SchedulerCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_scheduler::SchedulerCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_scheduler::SchedulerCommand_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "uid: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.uid);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.target);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "payload: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.payload);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "need_ack: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.need_ack);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SCHEDULER_MESSAGE_SCHEDULERCOMMAND_H
