// Generated by gencpp from file robot_scheduler/Subtask.msg
// DO NOT EDIT!


#ifndef ROBOT_SCHEDULER_MESSAGE_SUBTASK_H
#define ROBOT_SCHEDULER_MESSAGE_SUBTASK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robot_scheduler/Object.h>

namespace robot_scheduler
{
template <class ContainerAllocator>
struct Subtask_
{
  typedef Subtask_<ContainerAllocator> Type;

  Subtask_()
    : object()
    , source()
    , destination()  {
    }
  Subtask_(const ContainerAllocator& _alloc)
    : object(_alloc)
    , source(_alloc)
    , destination(_alloc)  {
  (void)_alloc;
    }



   typedef  ::robot_scheduler::Object_<ContainerAllocator>  _object_type;
  _object_type object;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _source_type;
  _source_type source;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _destination_type;
  _destination_type destination;





  typedef boost::shared_ptr< ::robot_scheduler::Subtask_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_scheduler::Subtask_<ContainerAllocator> const> ConstPtr;

}; // struct Subtask_

typedef ::robot_scheduler::Subtask_<std::allocator<void> > Subtask;

typedef boost::shared_ptr< ::robot_scheduler::Subtask > SubtaskPtr;
typedef boost::shared_ptr< ::robot_scheduler::Subtask const> SubtaskConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_scheduler::Subtask_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_scheduler::Subtask_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_scheduler::Subtask_<ContainerAllocator1> & lhs, const ::robot_scheduler::Subtask_<ContainerAllocator2> & rhs)
{
  return lhs.object == rhs.object &&
    lhs.source == rhs.source &&
    lhs.destination == rhs.destination;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_scheduler::Subtask_<ContainerAllocator1> & lhs, const ::robot_scheduler::Subtask_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_scheduler

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_scheduler::Subtask_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_scheduler::Subtask_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_scheduler::Subtask_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_scheduler::Subtask_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_scheduler::Subtask_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_scheduler::Subtask_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_scheduler::Subtask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6933e02dbcb5080f315b15eafcd4e885";
  }

  static const char* value(const ::robot_scheduler::Subtask_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6933e02dbcb5080fULL;
  static const uint64_t static_value2 = 0x315b15eafcd4e885ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_scheduler::Subtask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_scheduler/Subtask";
  }

  static const char* value(const ::robot_scheduler::Subtask_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_scheduler::Subtask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_scheduler/Object object\n"
"string source\n"
"string destination\n"
"\n"
"================================================================================\n"
"MSG: robot_scheduler/Object\n"
"uint16 object\n"
"uint16 target\n"
"bool decoy\n"
"geometry_msgs/PoseStamped pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::robot_scheduler::Subtask_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_scheduler::Subtask_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object);
      stream.next(m.source);
      stream.next(m.destination);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Subtask_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_scheduler::Subtask_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_scheduler::Subtask_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "object: ";
    Printer< ::robot_scheduler::Object_<ContainerAllocator> >::stream(s, indent + "  ", v.object);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "source: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.source);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "destination: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.destination);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SCHEDULER_MESSAGE_SUBTASK_H
