// Generated by gencpp from file robot_scheduler/TaskRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_SCHEDULER_MESSAGE_TASKREQUEST_H
#define ROBOT_SCHEDULER_MESSAGE_TASKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robot_scheduler/Subtask.h>

namespace robot_scheduler
{
template <class ContainerAllocator>
struct TaskRequest_
{
  typedef TaskRequest_<ContainerAllocator> Type;

  TaskRequest_()
    : subtasks()
    , execute_on()  {
    }
  TaskRequest_(const ContainerAllocator& _alloc)
    : subtasks(_alloc)
    , execute_on(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::robot_scheduler::Subtask_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::robot_scheduler::Subtask_<ContainerAllocator> >> _subtasks_type;
  _subtasks_type subtasks;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _execute_on_type;
  _execute_on_type execute_on;





  typedef boost::shared_ptr< ::robot_scheduler::TaskRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_scheduler::TaskRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TaskRequest_

typedef ::robot_scheduler::TaskRequest_<std::allocator<void> > TaskRequest;

typedef boost::shared_ptr< ::robot_scheduler::TaskRequest > TaskRequestPtr;
typedef boost::shared_ptr< ::robot_scheduler::TaskRequest const> TaskRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_scheduler::TaskRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_scheduler::TaskRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_scheduler::TaskRequest_<ContainerAllocator1> & lhs, const ::robot_scheduler::TaskRequest_<ContainerAllocator2> & rhs)
{
  return lhs.subtasks == rhs.subtasks &&
    lhs.execute_on == rhs.execute_on;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_scheduler::TaskRequest_<ContainerAllocator1> & lhs, const ::robot_scheduler::TaskRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_scheduler

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_scheduler::TaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_scheduler::TaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_scheduler::TaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_scheduler::TaskRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_scheduler::TaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_scheduler::TaskRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_scheduler::TaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d4c07a22d46edc9f78c6294bee4a791a";
  }

  static const char* value(const ::robot_scheduler::TaskRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd4c07a22d46edc9fULL;
  static const uint64_t static_value2 = 0x78c6294bee4a791aULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_scheduler::TaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_scheduler/TaskRequest";
  }

  static const char* value(const ::robot_scheduler::TaskRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_scheduler::TaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_scheduler/Subtask[] subtasks\n"
"string[] execute_on\n"
"\n"
"================================================================================\n"
"MSG: robot_scheduler/Subtask\n"
"robot_scheduler/Object object\n"
"string source\n"
"string destination\n"
"\n"
"================================================================================\n"
"MSG: robot_scheduler/Object\n"
"uint16 object\n"
"uint16 target\n"
"bool decoy\n"
"geometry_msgs/PoseStamped pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::robot_scheduler::TaskRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_scheduler::TaskRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.subtasks);
      stream.next(m.execute_on);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_scheduler::TaskRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_scheduler::TaskRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "subtasks: ";
    if (v.subtasks.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.subtasks.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::robot_scheduler::Subtask_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.subtasks[i]);
    }
    if (v.subtasks.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "execute_on: ";
    if (v.execute_on.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.execute_on.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.execute_on[i]);
    }
    if (v.execute_on.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SCHEDULER_MESSAGE_TASKREQUEST_H
